import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Box, Container} from "@mui/material"
// import Sidebar from "../components/Layout/Sidebar/Sidebar";
import Header from "../components/Layout/Header/Header";
import "./globals.css";
import { Padding } from "@mui/icons-material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fit Control",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen bg-gradient-to-b from-slate-200 to-slate-100">
        <Container maxWidth="xl" className="flex flex-col h-screen " sx={{padding: 0}}>
          <Header />
        </Container>
      </body>
    </html>
  );
}
